ffix include files

diff --git a/bin/giter-common-functions b/bin/giter-common-functions
--- a/bin/giter-common-functions
+++ b/bin/giter-common-functions
@@ -17,6 +17,8 @@
 # along with this program. If not, see <http://www.gnu.org/licenses/>.
 #
 
+. $PROGDIR/giter-sh-functions
+
 estrlist()
 {
         $PROGDIR/giter-estrlist "$@"
@@ -37,4 +39,63 @@ get_root_git_dir()
         local DIR=$(git rev-parse --git-dir 2>/dev/null)/../ || return
         readlink -f "$DIR" 2>/dev/null || realpath "$DIR"
         # FIXME: 1) can return / with good status 2) no one check status later
+}
+
+# TODO: move to separate gear file
+# TODO: rewrite with get_gear_rules_by_spec in mind
+get_gear_rules()
+{
+	local DIR="$1"
+	[ -z "$IGNOREGEAR" ] || return 1
+	[ -f "$DIR" ] && DIR=$(dirname "$DIR")
+	[ -n "$DIR" ] && cd $DIR
+	local GITDIR=$(get_root_git_dir)
+	[ -n "$DIR" ] && cd - >/dev/null
+	local rules="$GITDIR/.gear/rules"
+	[ -r "$rules" ] || rules="$GITDIR/.gear-rules"
+	[ -r "$rules" ] || return
+	echo $rules
+}
+
+
+# Usage: is_gear [path_to_spec|dir_inside_git]
+is_gear()
+{
+	get_gear_rules $@ >/dev/null
+}
+
+filter_gear_name()
+{
+	sed -e "s|\+|plus|g"
+}
+
+# FIXME: use in rpmbs, fix for package name from spec
+get_gear_name()
+{
+	local gitdir=$(get_root_git_dir)
+	[ -n "$gitdir" ] || return
+	basename "$gitdir" | filter_gear_name
+}
+
+get_girar_host_from_ssh()
+{
+	grep -i "host[\t ]\+" ~/.ssh/config | sed "s|.*host[\t ]*||gi" | grep "^git\." | head -n1
+}
+
+# load user config file
+if [ -f ~/.config/giter ] ; then
+	. ~/.config/giter
+fi
+
+if [ -z "$GIRARHOST" ] ; then
+	# set default GIRARHOST from ~/.ssh/config
+	GIRARHOST=$(get_girar_host_from_ssh)
+	[ -n "$GIRARHOST" ] || fatal "Can't get default girar alias (like git.alt) from ~/.ssh/config"
+fi
+
+
+# TODO: merge with sh-functions
+echocon()
+{
+	tty -s && echo "$@"
 }
