grebase: rewrite to use real commit id, not number in a list

diff --git a/bin/grebase b/bin/grebase
--- a/bin/grebase
+++ b/bin/grebase
@@ -1,7 +1,7 @@
 #!/bin/sh
 #
-# Copyright (C) 2013-2014  Etersoft
-# Copyright (C) 2013-2014  Vitaly Lipatov <lav@etersoft.ru>
+# Copyright (C) 2013-2015  Etersoft
+# Copyright (C) 2013-2015  Vitaly Lipatov <lav@etersoft.ru>
 #
 # This program is free software: you can redistribute it and/or modify
 # it under the terms of the GNU Affero General Public License as published by
@@ -21,6 +21,7 @@ PROGDIR=$(dirname $0)
 [ "$PROGDIR" = "." ] && PROGDIR=$(pwd)
 
 . $PROGDIR/giter-common-functions
+. $PROGDIR/giter-git-functions
 
 
 # Do git rebase -i
@@ -32,10 +33,18 @@ if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
 	exit 0
 fi
 
+FORCE=
+if [ "$1" = "-f" ] ; then
+	FORCE=1
+fi
+
+set_merge_ff
+
 NN=$1
 if [ -z "$NN" ] ; then
 	echo "Will do commit rebase. Last commit list:"
-	git log --pretty=format:"%s, %cd" | head -n 20 | cat -n
+	tmpfile=$(mktemp) || fatal
+	git log --pretty=format:"%h %s, %cd" | head -n 20 | tee $tmpfile | cat -n
 	echo "Input line number (next after needed) or Enter to exit:"
 	read NN other
 	# try convert to numeric
@@ -43,9 +52,8 @@ if [ -z "$NN" ] ; then
 	[ "$NN" = "0" ] && fatal "Incorrect number"
 fi
 
-set_merge_ff
+commit=$(cat $tmpfile | sed -n "${NN}p" | sed -e "s| .*||g")
+[ -n "$commit" ] || fatal "Logic error can't find commit $NN in $(cat $tmpfile)"
+rm -f $tmpfile
 
-# TODO: select from commit list
-CID="HEAD~$NN"
-echo $CID
-docmd git rebase -i $CID
+docmd git rebase -i "$commit^"
